### ISSUE TITLE
Custom element properties are not accessible

### ISSUE THREAD

**Issue by dios-david** [WebReflection/basicHTML#41]
I'm experimenting with basicHTML to render custom elements with SSR and I'm facing with an issue. Probably I'm doing something wrong, so I made this simplified code for demonstration:

```js
const { init, HTMLElement } = require('basichtml');
const { customElements, document } = init();

customElements.define('test-component', class TestComponent extends HTMLElement {
    connectedCallback() {
        this.innerHTML = `Hello ${this.getAttribute('greet')}!`;
    }
});

document.body.innerHTML = '<body><test-component greet="David"></test-component></body>';

console.log(document.toString());
```

The output is:
```html
<!DOCTYPE html><html><body><test-component greet="David">Hello null!</test-component></body></html>
```

While I'm expecting this (running in a browser the output matches this):
```html
<!DOCTYPE html><html><body><test-component greet="David">Hello David!</test-component></body></html>
```

Can somebody please tell me what am I doing wrong?

**Comment by WebReflection** [comment]
Thanks. `v1.1.0` should've fixed this 👋

**Comment by dios-david** [comment]
Thanks for the quick fix, but after upgrading basihtml I get this error when running the same script:

```
D:\D\Workspace\dcmp\node_modules\basichtml\src\Element.js:37
      if (node.nodeName === name)
               ^

TypeError: Cannot read property 'nodeName' of undefined
    at Object.onclosetag (D:\D\Workspace\dcmp\node_modules\?[4mbasichtml?[24m\src\Element.js:37:16)
    at Parser.onclosetag (D:\D\Workspace\dcmp\node_modules\?[4mhtmlparser2?[24m\lib\Parser.js:220:41)
    at Tokenizer._emitToken (D:\D\Workspace\dcmp\node_modules\?[4mhtmlparser2?[24m\lib\Tokenizer.js:960:20)
    at Tokenizer._stateInCloseingTagName (D:\D\Workspace\dcmp\node_modules\?[4mhtmlparser2?[24m\lib\Tokenizer.js:214:14)
    at Tokenizer._parse (D:\D\Workspace\dcmp\node_modules\?[4mhtmlparser2?[24m\lib\Tokenizer.js:714:18)
    at Tokenizer.write (D:\D\Workspace\dcmp\node_modules\?[4mhtmlparser2?[24m\lib\Tokenizer.js:699:10)
    at Parser.write (D:\D\Workspace\dcmp\node_modules\?[4mhtmlparser2?[24m\lib\Parser.js:363:21)
    at parseInto (D:\D\Workspace\dcmp\node_modules\?[4mbasichtml?[24m\src\Element.js:44:11)
    at HTMLElement.set innerHTML [as innerHTML] (D:\D\Workspace\dcmp\node_modules\?[4mbasichtml?[24m\src\Element.js:250:5)
    at Object.<anonymous> (D:\D\Workspace\dcmp\server\app.js:36:25)
```

**Comment by WebReflection** [comment]
can you please try with v1.1.1 ? thanks

**Comment by dios-david** [comment]
Something is still wrong :(

```
TypeError: Cannot read property 'nodeName' of undefined
    at Object.onclosetag (d:\D\Workspace\dcmp\node_modules\basichtml\src\Element.js:37:16)
    at Parser.onclosetag (d:\D\Workspace\dcmp\node_modules\htmlparser2\lib\Parser.js:220:41)
    at Tokenizer._emitToken (d:\D\Workspace\dcmp\node_modules\htmlparser2\lib\Tokenizer.js:960:20)
    at Tokenizer._stateInCloseingTagName (d:\D\Workspace\dcmp\node_modules\htmlparser2\lib\Tokenizer.js:214:14)
    at Tokenizer._parse (d:\D\Workspace\dcmp\node_modules\htmlparser2\lib\Tokenizer.js:714:18)
    at Tokenizer.write (d:\D\Workspace\dcmp\node_modules\htmlparser2\lib\Tokenizer.js:699:10)
    at Parser.write (d:\D\Workspace\dcmp\node_modules\htmlparser2\lib\Parser.js:363:21)
    at parseInto (d:\D\Workspace\dcmp\node_modules\basichtml\src\Element.js:44:11)
    at HTMLElement.set innerHTML [as innerHTML] (d:\D\Workspace\dcmp\node_modules\basichtml\src\Element.js:250:5)
    at Object.parcelRequire.app.js (d:\D\Workspace\dcmp\dist\server\app.js:156:25)
```

**Comment by dios-david** [comment]
It works fine now 🎉 Thanks for the quick help!
